<class 'dict'>
0.3926919518963922
0.3371877890841813
Traceback (most recent call last):
  File "/Users/joseangelcazares/Desktop/Pokerbots/pokerbots-ramen/ramen-2/player.py", line 180, in <module>
    run_bot(Player(), parse_args())
  File "/Users/joseangelcazares/Desktop/Pokerbots/pokerbots-ramen/ramen-2/skeleton/runner.py", line 130, in run_bot
    runner.run()
  File "/Users/joseangelcazares/Desktop/Pokerbots/pokerbots-ramen/ramen-2/skeleton/runner.py", line 105, in run
    action = self.pokerbot.get_action(game_state, round_state, active)
  File "/Users/joseangelcazares/Desktop/Pokerbots/pokerbots-ramen/ramen-2/player.py", line 153, in get_action
    if(my_cards in get_playable_hole_cards(self.prob_table, self.all_hands)):   #call good hands 
  File "/Users/joseangelcazares/Desktop/Pokerbots/pokerbots-ramen/ramen-2/prob.py", line 34, in get_playable_hole_cards
    elif prob_table[(c[0].rank, c[1].rank)] >= 0.5:
KeyError: (0, 0)
